### PR TITLE
add Chinese company sql component

### PR DESCRIPTION
**Pull request by wengzhenjie**
#206 

add company info to config

### CODE REVIEW

**Comment by wengzhenjie** [comment]
I guess the error may be related to the type of id on `join`.

**Comment by frank-zsy** [comment]
Maybe, I think I should modify the server side to return the error detail instead of status 500.

**Comment by frank-zsy** [comment]
I still think we can use a single component to generate Chinese and Chinese company status. We can return all repo data as result and group by company in post-processor, because I think the result may not be too large since there are only several fields for one repo.

**Comment by wengzhenjie** [comment]
I see. I will change it.

**Comment by wengzhenjie** [comment]
`post-processor` is required to return string. But I want to return list. How can I do for report_template?

**Comment by frank-zsy** [comment]
Actually you can also return an object and use key-value in template file. like `return {"c": "a"}` and in template file you can use `slq.text.c` to get the value.

**Comment by wengzhenjie** [comment]
OK. Thanks.

**Comment by frank-zsy** [comment]
As we have no `pre-processor` implementation for CI part, I will merge this PR to test first.

/approve

**Pull request merged**
