### PR TITLE
sqls: add sql of developer (#276)

### PR DESCRIPTION
**Pull request by chenxi112**
"sqls: add sql of developer (#276)"

### CODE REVIEW

**Comment by frank-zsy** [comment]
Can you describe what the output is? So we can review the SQL component due to the description.

**Comment by chenxi112** [comment]
It will output top 20 developers according to their total activity. And for each developer,  it will output the top 10 most active repositories, their activity, issue-comment,  open_issue, open_pull, pull_review_comment, merge_pull, pull comments, pull_additions and pull_deletions.

**Comment by frank-zsy** [comment]
But I can not quite understand your SQL here. I think there are some points need to be considered.

- This a case study component, so we may not need to constrain the repo count, all repos in the case study need to be returned.
- For every repo in the case study, we may return top N most active developers in the repo during this year.
- Your SQL contains some errors and I can not understand the logic here, we may discuss this later in the meeting.

**Comment by frank-zsy** [comment]
I am not sure this is correct or not, I can't tell from my eyes. I will merge this PR for testing as we don't have case study CI right now.

/approve

**Pull request merged**
