### PR TITLE
[Feature] Language distribution of Top 100000 repos

### PR DESCRIPTION
**Pull request by xiaoya-Esther**
The result would have four columns if everything works well:
The first column refers to Top20 most popular languages within the top 100000 active repos
The second column refers to the number of repos(top100000) who use that language
The third column is the name of the most active repo that use this language and the last is the activity of the repo.

Note that I haven't tested it locally because the four-star nodes of ECNU are running into an issue currently:(

### CODE REVIEW

**Comment by frank-zsy** [comment]
That's OK to test the SQL in PR, I assume the SQL will have some redundant query but I can not be sure, I will run the SQL to check the result first.

/run-sql

**Comment by frank-zsy** [comment]
There are some errors and I will check what went wrong.

**Comment by xiaoya-Esther** [comment]
OK, thanks!
I will check it too

**Comment by frank-zsy** [comment]
There are several errors in your SQL, I can't find them all since the SQL is too complex. I think we can make the SQL quite simpler to avoid errors.

Why didn't you just use the activity SQL and `GROUP BY` language to get the result?

**Comment by xiaoya-Esther** [comment]
I wish to return the most active repo that uses the corresponding language and his activity, so I wrote the activity SQL two times to make a LEFT JOIN, the left table is for aggregating languages and counts, and the right table for seeking out the most active repo who use the language

**Comment by frank-zsy** [comment]
I understand and actually when you get the activity table, all data you need is already in there, so you only need to use current aggregation function to get the result, I will give you an example which I also add developer count in it that works fine on my local env.

The rendered SQL is:

```
SELECT 
    repo_language, 
    COUNT(*) AS count, 
    argMax(repo_name, repo_activity) AS top_repo, 
    max(repo_activity) AS activity, 
    SUM(actor_count) AS actor_count
FROM 
(
    SELECT 
        contribute_list.repo_id AS repo_id, 
        anyLast(contribute_list.repo_name) AS repo_name, 
        max(contribute_list.repo_language) AS repo_language, 
        round(sum(sqrt(contribute_list.score)), 2) AS repo_activity, 
        COUNTDistinct(contribute_list.actor_id) AS actor_count
    FROM 
    (
        SELECT 
            icc.repo_id AS repo_id, 
            icc.repo_name AS repo_name, 
            icc.actor_id AS actor_id, 
            mpc.repo_language AS repo_language, 
            ((((1 * icc.count) + (2 * oic.count)) + (3 * opc.count)) + (4 * rcc.count)) + (5 * mpc.count) AS score
        FROM 
        (
            SELECT 
                repo_id, 
                anyLast(repo_name) AS repo_name, 
                actor_id, 
                COUNT(*) AS count
            FROM github_log.year2020
            WHERE (type = 'IssueCommentEvent') AND (action = 'created')
            GROUP BY 
                repo_id, 
                actor_id
        ) AS icc
        LEFT JOIN 
        (
            SELECT 
                repo_id, 
                actor_id, 
                COUNT(*) AS count
            FROM github_log.year2020
            WHERE (type = 'IssuesEvent') AND (action = 'opened')
            GROUP BY 
                repo_id, 
                actor_id
        ) AS oic ON (icc.repo_id = oic.repo_id) AND (icc.actor_id = oic.actor_id)
        LEFT JOIN 
        (
            SELECT 
                repo_id, 
                actor_id, 
                COUNT(*) AS count
            FROM github_log.year2020
            WHERE (type = 'PullRequestEvent') AND (action = 'opened')
            GROUP BY 
                repo_id, 
                actor_id
        ) AS opc ON (icc.repo_id = opc.repo_id) AND (icc.actor_id = opc.actor_id)
        LEFT JOIN 
        (
            SELECT 
                repo_id, 
                actor_id, 
                COUNT(*) AS count
            FROM github_log.year2020
            WHERE (type = 'PullRequestReviewCommentEvent') AND (action = 'created')
            GROUP BY 
                repo_id, 
                actor_id
        ) AS rcc ON (icc.repo_id = rcc.repo_id) AND (icc.actor_id = rcc.actor_id)
        LEFT JOIN 
        (
            SELECT 
                repo_id, 
                issue_author_id AS actor_id, 
                max(repo_language) AS repo_language, 
                COUNT(*) AS count
            FROM github_log.year2020
            WHERE (type = 'PullRequestEvent') AND (action = 'closed') AND (pull_merged = 1)
            GROUP BY 
                repo_id, 
                actor_id
        ) AS mpc ON (icc.repo_id = mpc.repo_id) AND (icc.actor_id = mpc.actor_id)
    ) AS contribute_list
    GROUP BY repo_id
    ORDER BY repo_activity DESC
    LIMIT 100000
)
WHERE repo_language != ''
GROUP BY repo_language
ORDER BY count DESC
LIMIT 20
```

Make sure to add a blank space between `LIMIT` and the param.

**Comment by frank-zsy** [comment]
By the way, the result is

image

I assume it is OK but there may some repos without language information.

**Comment by xiaoya-Esther** [comment]
I see, I've made it too complicated and that may be caused by not being too familiar with what will be returned by the `GROUP BY` function. Thanks, I will edit the commit later!

**Comment by frank-zsy** [comment]
No problem, happy coding. And note that the `actor_count` is not distinct so it means person times. Like one developer's activity on different repos will be counted multiple times, no matter the language is same or not, but I think it is also reasonable.

**Comment by xiaoya-Esther** [comment]
so can I take it as the `actor_count` here actually means how many actors have been active in the repo, instead of how many actors have use the language?

**Comment by frank-zsy** [comment]
Since I use `SUM` to aggregate the `actor_count` column so it does not mean developer count active in the most active repo but all developer count active on repos with this language and the accounts are not distinct.

**Comment by xiaoya-Esther** [comment]
Oh yes, I think I get it

**Comment by frank-zsy** [comment]
> /sql-run

You don't have the permission to execute SQL~

**Comment by xiaoya-Esther** [comment]
Cool, thanks!

**Comment by frank-zsy** [comment]
@xiaoya-Esther You should also inject the result into `REPORT_TEMPLATE` file~

**Comment by xiaoya-Esther** [comment]
OK, I will do that

**Comment by frank-zsy** [comment]
Great, we will wait for it.

**Pull request merged**
