### PR TITLE
[Docs] Add repo activity top 10 into the report template

### PR DESCRIPTION
**Pull request by sunshinemingo**

### CODE REVIEW

**Comment by frank-zsy** [comment]
Is this PR completed? Right now the `text` part of `activity-repo-top` is not valid yet.

**Comment by frank-zsy** [comment]
My laptop is not online right now, you can run SQL later after 3pm UTC+8

**Comment by sunshinemingo** [comment]
OK, I get it

**Comment by frank-zsy** [comment]
Great improve, thx, please add PR body next time.
fix #82 
/sql-verified
/approve

**Comment by sunshinemingo** [comment]
OK, I will pay attention to it next time.

**Pull request merged**
