### PR TITLE
[Feature] Add top developers rank list

### LINKED ISSUE #205: [Feature] Global developer analysis should be added.
Now we already have a global rank list for top 10 repos, but we still need a similar component to generate global developers rank list too. We may also use the traditional activity calculation method and add the result into the main report.

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: Frankzhaopku <syzhao1988@126.com>

Add top developers rank list to report, total activity, participant repo count, open issue count, issue comment count, open pull count, pull review comment count, merged pull count included.

close #205

### CODE REVIEW

**Comment by frank-zsy** [comment]
Top developers analysis result will be generated in about 1 minute.

**Comment by sunshinemingo** [comment]
/approve
thanks for the feature

**Pull request merged**
