### PR TITLE
[Fix] Several changes to Chinese repo 

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: Frankzhaopku <syzhao1988@126.com>

Fix several things about Chinese repo SQL component.

For hypertrons `auto_update_report` component
- Need to pass self component config into post processor as the third param, the second param is the global default render params.

For Chinese SQL component:
- As returned `id` columns are in string type, need to change `org_id_company_map` and `repo_id_company_map` key to string type, otherwise will not find the correct company.
- As returned integer number columns are in string type, need to use `parseInt` to change into `int` because need to calculate later.
- the `company_info_list` is not in correct format, need to change into an array with array elements and the `activity` needs to be fixed to 2 digits as add operation will do some tricks to float value.

### CODE REVIEW

**Comment by frank-zsy** [comment]
@wengzhenjie Can you review this one?

**Comment by frank-zsy** [comment]
> /sql-run

You don't need to run this SQL because CI still not support hypertrons and pre processor, only look into the changes and see if they make sense.

**Review by wengzhenjie — APPROVED** [review]

**Review by wengzhenjie — APPROVED** [review]

**Comment by wengzhenjie** [comment]
These changes are useful. Company_info_list actually is two-dimensional array. And some fields also need to be converted. Thank you fixing them.

**Comment by frank-zsy** [comment]
Alright, I will force merge this PR to see the result.

**Pull request merged**
