### PR TITLE
[Docs] add incubate procedure

### PR DESCRIPTION
**Pull request by sunshinemingo**
add incubate procedure of LF AI projects

### CODE REVIEW

**Comment by frank-zsy** [comment]
Is there a Chinese version of this document? Or we can find someone to translate this.

**Comment by frank-zsy** [comment]
Great, you may append the translate version to current file.

**Comment by sunshinemingo** [comment]
The Chinese version of the document has add into current file.

**Comment by frank-zsy** [comment]
Great contribution, may I approve this PR right now or you will add landscape image too?

**Comment by sunshinemingo** [comment]
The landscape image has added.
Sorry, I forgot it just now.

**Pull request merged**
