### PR TITLE
add company repo_count&developer_count

### PR DESCRIPTION
**Pull request by wengzhenjie**

### CODE REVIEW

**Comment by frank-zsy** [comment]
@sunshinemingo As the CI component does not support pre processor yet, the /sql-run won't return correct result, I will add it first.

**Comment by sunshinemingo** [comment]
> @sunshinemingo As the CI component does not support pre processor yet, the /sql-run won't return correct result, I will add it first.

OK, I get it.

**Comment by frank-zsy** [comment]
The returned SQL result is too long to comment to a PR, I will merge the PR, I think it is OK.

/approve

**Pull request merged**
