### PR TITLE
[Docs] add ASF report template and manifest 

### PR DESCRIPTION
**Pull request by heming6666**
- Add ASF report template

- And ASF case study manifest

Signed-off-by: LinHaiming <lhming23@outlook.com>

### CODE REVIEW

**Comment by heming6666** [comment]
@frank-zsy `Servicecomb` project includes several repositories in github. Which one should be counted as the main repositories ? `servicecomb-java-chassis` is chosen currently.

https://github.com/search?p=1&q=org%3Aapache+servicecomb&type=Repositories

**Comment by frank-zsy** [comment]
> @frank-zsy `Servicecomb` project includes several repositories in github. Which one should be counted as the main repositories ? `servicecomb-java-chassis` is chosen currently.
> 
> https://github.com/search?p=1&q=org%3Aapache+servicecomb&type=Repositories

I think we need to @WillemJiang to tell us which to choose.

**Comment by heming6666** [comment]
> I think we need to @WillemJiang to tell us which to choose.

I consult @WillemJiang and the answer is `servicecomb-java-chassis`. Thanks @WillemJiang.

**Comment by frank-zsy** [comment]
Is there any update on this PR? It has been in draft status for 5 days. @heming6666

**Comment by heming6666** [comment]
Sorry for the delay.

This PR is ready for review now. @frank-zsy @sunshinemingo @wengzhenjie please help review this PR, many thanks。

**Pull request merged**
